
    <html>
    <head>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
                text-align: left;
            }
            th, td {
                padding: 12px;
                border: 1px solid #ddd;
            }
            th {
                background-color: #f4f4f4;
            }
            tr:nth-child(even) {
                background-color: #f9f9f9;
            }
            .reason {
                white-space: pre-wrap;
                word-wrap: break-word;
            }
        </style>
    </head>
    <body>
        <h2>Unit Test Results</h2>
        <p>Test run date: 2025-03-26T23:00:45.518163</p>
        <style type="text/css">
#T_45e35_row0_col0, #T_45e35_row0_col1, #T_45e35_row0_col2, #T_45e35_row1_col0, #T_45e35_row1_col1, #T_45e35_row1_col2, #T_45e35_row2_col0, #T_45e35_row2_col1, #T_45e35_row2_col2, #T_45e35_row3_col0, #T_45e35_row3_col1, #T_45e35_row3_col2, #T_45e35_row5_col0, #T_45e35_row5_col1, #T_45e35_row5_col2, #T_45e35_row6_col0, #T_45e35_row6_col1, #T_45e35_row6_col2, #T_45e35_row13_col0, #T_45e35_row13_col1, #T_45e35_row13_col2, #T_45e35_row15_col0, #T_45e35_row15_col1, #T_45e35_row15_col2, #T_45e35_row17_col0, #T_45e35_row17_col1, #T_45e35_row17_col2, #T_45e35_row22_col0, #T_45e35_row22_col1, #T_45e35_row22_col2 {
  background-color: #f8d7da;
}
#T_45e35_row4_col0, #T_45e35_row4_col1, #T_45e35_row4_col2, #T_45e35_row7_col0, #T_45e35_row7_col1, #T_45e35_row7_col2, #T_45e35_row8_col0, #T_45e35_row8_col1, #T_45e35_row8_col2, #T_45e35_row9_col0, #T_45e35_row9_col1, #T_45e35_row9_col2, #T_45e35_row11_col0, #T_45e35_row11_col1, #T_45e35_row11_col2, #T_45e35_row12_col0, #T_45e35_row12_col1, #T_45e35_row12_col2, #T_45e35_row19_col0, #T_45e35_row19_col1, #T_45e35_row19_col2, #T_45e35_row20_col0, #T_45e35_row20_col1, #T_45e35_row20_col2, #T_45e35_row21_col0, #T_45e35_row21_col1, #T_45e35_row21_col2, #T_45e35_row23_col0, #T_45e35_row23_col1, #T_45e35_row23_col2, #T_45e35_row24_col0, #T_45e35_row24_col1, #T_45e35_row24_col2, #T_45e35_row25_col0, #T_45e35_row25_col1, #T_45e35_row25_col2, #T_45e35_row26_col0, #T_45e35_row26_col1, #T_45e35_row26_col2, #T_45e35_row27_col0, #T_45e35_row27_col1, #T_45e35_row27_col2, #T_45e35_row28_col0, #T_45e35_row28_col1, #T_45e35_row28_col2, #T_45e35_row29_col0, #T_45e35_row29_col1, #T_45e35_row29_col2, #T_45e35_row30_col0, #T_45e35_row30_col1, #T_45e35_row30_col2, #T_45e35_row31_col0, #T_45e35_row31_col1, #T_45e35_row31_col2 {
  background-color: #d4edda;
}
#T_45e35_row10_col0, #T_45e35_row10_col1, #T_45e35_row10_col2, #T_45e35_row14_col0, #T_45e35_row14_col1, #T_45e35_row14_col2, #T_45e35_row16_col0, #T_45e35_row16_col1, #T_45e35_row16_col2, #T_45e35_row18_col0, #T_45e35_row18_col1, #T_45e35_row18_col2 {
  background-color: #fff3cd;
}
</style>
<table id="T_45e35">
  <thead>
    <tr>
      <th class="blank level0" >&nbsp;</th>
      <th id="T_45e35_level0_col0" class="col_heading level0 col0" >test</th>
      <th id="T_45e35_level0_col1" class="col_heading level0 col1" >status</th>
      <th id="T_45e35_level0_col2" class="col_heading level0 col2" >reason</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="T_45e35_level0_row0" class="row_heading level0 row0" >0</th>
      <td id="T_45e35_row0_col0" class="data row0 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_empty_item</td>
      <td id="T_45e35_row0_col1" class="data row0 col1" >FAIL</td>
      <td id="T_45e35_row0_col2" class="data row0 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 68, in test_empty_item
    Order("", 1)  # Item should not be empty
AssertionError: ValueError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row1" class="row_heading level0 row1" >1</th>
      <td id="T_45e35_row1_col0" class="data row1 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_invalid_id_negative</td>
      <td id="T_45e35_row1_col1" class="data row1 col1" >FAIL</td>
      <td id="T_45e35_row1_col2" class="data row1 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 78, in test_invalid_id_negative
    Order("Peach", 2)  # No direct way to set ID, but we can check indirectly
AssertionError: ValueError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row2" class="row_heading level0 row2" >2</th>
      <td id="T_45e35_row2_col0" class="data row2 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_invalid_item_type</td>
      <td id="T_45e35_row2_col1" class="data row2 col1" >FAIL</td>
      <td id="T_45e35_row2_col2" class="data row2 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 42, in test_invalid_item_type
    Order(123, 5)  # Item should be a string
AssertionError: TypeError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row3" class="row_heading level0 row3" >3</th>
      <td id="T_45e35_row3_col0" class="data row3 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_invalid_quantity_type</td>
      <td id="T_45e35_row3_col1" class="data row3 col1" >FAIL</td>
      <td id="T_45e35_row3_col2" class="data row3 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 47, in test_invalid_quantity_type
    Order("Orange", "two")  # Quantity should be an integer
AssertionError: TypeError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row4" class="row_heading level0 row4" >4</th>
      <td id="T_45e35_row4_col0" class="data row4 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_multiple_orders</td>
      <td id="T_45e35_row4_col1" class="data row4 col1" >PASS</td>
      <td id="T_45e35_row4_col2" class="data row4 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row5" class="row_heading level0 row5" >5</th>
      <td id="T_45e35_row5_col0" class="data row5 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_negative_quantity</td>
      <td id="T_45e35_row5_col1" class="data row5 col1" >FAIL</td>
      <td id="T_45e35_row5_col2" class="data row5 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 57, in test_negative_quantity
    Order("Peach", -1)  # Quantity should be non-negative
AssertionError: ValueError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row6" class="row_heading level0 row6" >6</th>
      <td id="T_45e35_row6_col0" class="data row6 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_null_item</td>
      <td id="T_45e35_row6_col1" class="data row6 col1" >FAIL</td>
      <td id="T_45e35_row6_col2" class="data row6 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\model\test_order_0.py", line 73, in test_null_item
    Order(None, 1)  # Item should not be None
AssertionError: TypeError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row7" class="row_heading level0 row7" >7</th>
      <td id="T_45e35_row7_col0" class="data row7 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_string_representation</td>
      <td id="T_45e35_row7_col1" class="data row7 col1" >PASS</td>
      <td id="T_45e35_row7_col2" class="data row7 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row8" class="row_heading level0 row8" >8</th>
      <td id="T_45e35_row8_col0" class="data row8 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_valid_order_creation</td>
      <td id="T_45e35_row8_col1" class="data row8 col1" >PASS</td>
      <td id="T_45e35_row8_col2" class="data row8 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row9" class="row_heading level0 row9" >9</th>
      <td id="T_45e35_row9_col0" class="data row9 col0" >OrderManagementSystem.app.model.test_order_0.TestOrder.test_zero_quantity</td>
      <td id="T_45e35_row9_col1" class="data row9 col1" >PASS</td>
      <td id="T_45e35_row9_col2" class="data row9 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row10" class="row_heading level0 row10" >10</th>
      <td id="T_45e35_row10_col0" class="data row10 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_all_after_saving_multiple_orders</td>
      <td id="T_45e35_row10_col1" class="data row10 col1" >ERROR</td>
      <td id="T_45e35_row10_col2" class="data row10 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 68, in test_find_all_after_saving_multiple_orders
    order1 = Order("Grapes", 4, id=4)
TypeError: __init__() got an unexpected keyword argument 'id'
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row11" class="row_heading level0 row11" >11</th>
      <td id="T_45e35_row11_col0" class="data row11 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_all_empty</td>
      <td id="T_45e35_row11_col1" class="data row11 col1" >PASS</td>
      <td id="T_45e35_row11_col2" class="data row11 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row12" class="row_heading level0 row12" >12</th>
      <td id="T_45e35_row12_col0" class="data row12 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_by_id_invalid</td>
      <td id="T_45e35_row12_col1" class="data row12 col1" >PASS</td>
      <td id="T_45e35_row12_col2" class="data row12 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row13" class="row_heading level0 row13" >13</th>
      <td id="T_45e35_row13_col0" class="data row13 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_by_id_negative_id</td>
      <td id="T_45e35_row13_col1" class="data row13 col1" >FAIL</td>
      <td id="T_45e35_row13_col2" class="data row13 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 54, in test_find_by_id_negative_id
    self.repository.find_by_id(-1)
AssertionError: ValueError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row14" class="row_heading level0 row14" >14</th>
      <td id="T_45e35_row14_col0" class="data row14 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_by_id_valid</td>
      <td id="T_45e35_row14_col1" class="data row14 col1" >ERROR</td>
      <td id="T_45e35_row14_col2" class="data row14 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 33, in test_find_by_id_valid
    order = Order("Banana", 2, id=2)
TypeError: __init__() got an unexpected keyword argument 'id'
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row15" class="row_heading level0 row15" >15</th>
      <td id="T_45e35_row15_col0" class="data row15 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_find_by_id_zero_id</td>
      <td id="T_45e35_row15_col1" class="data row15 col1" >FAIL</td>
      <td id="T_45e35_row15_col2" class="data row15 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 59, in test_find_by_id_zero_id
    self.repository.find_by_id(0)
AssertionError: ValueError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row16" class="row_heading level0 row16" >16</th>
      <td id="T_45e35_row16_col0" class="data row16 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_save_invalid_order</td>
      <td id="T_45e35_row16_col1" class="data row16 col1" >ERROR</td>
      <td id="T_45e35_row16_col2" class="data row16 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 49, in test_save_invalid_order
    self.repository.save(Order("Orange", 3, id=-1))
TypeError: __init__() got an unexpected keyword argument 'id'
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row17" class="row_heading level0 row17" >17</th>
      <td id="T_45e35_row17_col0" class="data row17 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_save_none_order</td>
      <td id="T_45e35_row17_col1" class="data row17 col1" >FAIL</td>
      <td id="T_45e35_row17_col2" class="data row17 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 64, in test_save_none_order
    self.repository.save(None)
AssertionError: TypeError not raised
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row18" class="row_heading level0 row18" >18</th>
      <td id="T_45e35_row18_col0" class="data row18 col0" >OrderManagementSystem.app.repository.test_in_memory_order_repository_0.TestInMemoryOrderRepository.test_save_valid_order</td>
      <td id="T_45e35_row18_col1" class="data row18 col1" >ERROR</td>
      <td id="T_45e35_row18_col2" class="data row18 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_in_memory_order_repository_0.py", line 27, in test_save_valid_order
    order = Order("Apple", 1, id=1)
TypeError: __init__() got an unexpected keyword argument 'id'
</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row19" class="row_heading level0 row19" >19</th>
      <td id="T_45e35_row19_col0" class="data row19 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_find_all_empty</td>
      <td id="T_45e35_row19_col1" class="data row19 col1" >PASS</td>
      <td id="T_45e35_row19_col2" class="data row19 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row20" class="row_heading level0 row20" >20</th>
      <td id="T_45e35_row20_col0" class="data row20 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_find_all_with_orders</td>
      <td id="T_45e35_row20_col1" class="data row20 col1" >PASS</td>
      <td id="T_45e35_row20_col2" class="data row20 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row21" class="row_heading level0 row21" >21</th>
      <td id="T_45e35_row21_col0" class="data row21 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_find_by_id_invalid</td>
      <td id="T_45e35_row21_col1" class="data row21 col1" >PASS</td>
      <td id="T_45e35_row21_col2" class="data row21 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row22" class="row_heading level0 row22" >22</th>
      <td id="T_45e35_row22_col0" class="data row22 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_find_by_id_valid</td>
      <td id="T_45e35_row22_col1" class="data row22 col1" >FAIL</td>
      <td id="T_45e35_row22_col2" class="data row22 col2" >Traceback (most recent call last):
  File "D:\Sai\EnhanceUnitTesting\tests\OrderManagementSystem\app\repository\test_order_repository_0.py", line 56, in test_find_by_id_valid
    self.assertEqual(found_order.item, "Apple")
AssertionError: 'Banana' != 'Apple'
- Banana
+ Apple

</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row23" class="row_heading level0 row23" >23</th>
      <td id="T_45e35_row23_col0" class="data row23 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_find_by_id_zero</td>
      <td id="T_45e35_row23_col1" class="data row23 col1" >PASS</td>
      <td id="T_45e35_row23_col2" class="data row23 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row24" class="row_heading level0 row24" >24</th>
      <td id="T_45e35_row24_col0" class="data row24 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_save_invalid_order_type</td>
      <td id="T_45e35_row24_col1" class="data row24 col1" >PASS</td>
      <td id="T_45e35_row24_col2" class="data row24 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row25" class="row_heading level0 row25" >25</th>
      <td id="T_45e35_row25_col0" class="data row25 col0" >OrderManagementSystem.app.repository.test_order_repository_0.TestOrderRepository.test_save_valid_order</td>
      <td id="T_45e35_row25_col1" class="data row25 col1" >PASS</td>
      <td id="T_45e35_row25_col2" class="data row25 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row26" class="row_heading level0 row26" >26</th>
      <td id="T_45e35_row26_col0" class="data row26 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_create_order_negative_quantity</td>
      <td id="T_45e35_row26_col1" class="data row26 col1" >PASS</td>
      <td id="T_45e35_row26_col2" class="data row26 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row27" class="row_heading level0 row27" >27</th>
      <td id="T_45e35_row27_col0" class="data row27 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_create_order_valid</td>
      <td id="T_45e35_row27_col1" class="data row27 col1" >PASS</td>
      <td id="T_45e35_row27_col2" class="data row27 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row28" class="row_heading level0 row28" >28</th>
      <td id="T_45e35_row28_col0" class="data row28 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_create_order_zero_quantity</td>
      <td id="T_45e35_row28_col1" class="data row28 col1" >PASS</td>
      <td id="T_45e35_row28_col2" class="data row28 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row29" class="row_heading level0 row29" >29</th>
      <td id="T_45e35_row29_col0" class="data row29 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_get_all_orders</td>
      <td id="T_45e35_row29_col1" class="data row29 col1" >PASS</td>
      <td id="T_45e35_row29_col2" class="data row29 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row30" class="row_heading level0 row30" >30</th>
      <td id="T_45e35_row30_col0" class="data row30 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_get_order_by_id_invalid</td>
      <td id="T_45e35_row30_col1" class="data row30 col1" >PASS</td>
      <td id="T_45e35_row30_col2" class="data row30 col2" >None</td>
    </tr>
    <tr>
      <th id="T_45e35_level0_row31" class="row_heading level0 row31" >31</th>
      <td id="T_45e35_row31_col0" class="data row31 col0" >OrderManagementSystem.app.service.test_order_service_0.TestOrderService.test_get_order_by_id_valid</td>
      <td id="T_45e35_row31_col1" class="data row31 col1" >PASS</td>
      <td id="T_45e35_row31_col2" class="data row31 col2" >None</td>
    </tr>
  </tbody>
</table>

    </body>
    </html>
    